### ISSUE TITLE
Reloading causes stress from cigarettes to duplicate into normal stress

### ISSUE THREAD

**Issue by demiurgeQuantified** [demiurgeQuantified/StatsAPI#10]
When loading a save game, a character's stress from cigarettes is copied into their regular stress. For example, a character with 0.2 cigarette stress gains an additional 0.2 stress upon loading. My hope was to fix this for v0.4.5 but I haven't been able to find an obvious cause or even opportunity for this to be happening.

**Comment by Diakon5** [comment]
From what I remember, Stress from cigarettes and stress from other sources are kept separately and then combined for a total stress value... Reading through the stress module, I haven't found any reimplementation of the smoker trait, which I think is the likely cause of the issue

**Comment by demiurgeQuantified** [comment]
yeah, that was actually the cause of #5 - but since then we use field access to get the pre-cigarette stress value, so it's unclear when this gets crossed over, and why it only happens at game load (only during the first tick maybe?)

**Comment by Diakon5** [comment]
Java logic always runs before the Lua logic... Still, would have to have a solid sit down to find the root cause of this...

**Comment by demiurgeQuantified** [comment]
vanilla bug
