### ISSUE TITLE
Gap between moodles/likely invisible moodle?

### ISSUE THREAD

**Issue by demiurgeQuantified** [demiurgeQuantified/StatsAPI#11]
![image](https://github.com/user-attachments/assets/0aa64b89-66d9-4333-b394-74edeb24e7f8)
Happening nearly constantly on a new server, don't recall it happening on a previous server with almost identical mod list

**Comment by demiurgeQuantified** [comment]
i just can't reproduce this in debug mode, whatever causes it must be something that happens in regular gameplay but not in test conditions. the only reason i can see this happening is if a moodle ends up in the showingMoodles list twice - the render offset is set in a loop through that list, so if a moodle appeared multiple times in the list, it would render in the last position only. however, it doesn't seem possible for this to happen?

**Comment by demiurgeQuantified** [comment]
issue still occurs after patch

**Comment by demiurgeQuantified** [comment]
tiredness moodle did not show up at all while the issue was ongoing, is preventing duplicates just stopping the working moodle from appearing?

**Comment by RF-PT** [comment]
Hello "Albion"!

I wanted to report the same issue, the only diference is i'm using the Plain Moodles mod.

Sometimes the gap between the moodles dont appear but most of the times its there, i cant replicate it as well, is has happened outside, it has happened inside while chilling at base.

I really hope that you have a solution for this, i even have tried to remove the moodle mods i have, change the load order, etc, nothing helps, i'm currently with 200h in testing my modlist and going strong, its the first issue i cant "fix".

Cheers from Portugal.

**Comment by demiurgeQuantified** [comment]
![image](https://github.com/user-attachments/assets/5ae50a5b-3c4e-4c38-a606-cfcd7df2b7ed)
:(

**Comment by demiurgeQuantified** [comment]
yeah this really needs to be fixed - this time it was extremely noticeably gameplay affecting - the affected moodles were my thirst and hunger moodle, so i could not tell when i had to eat or drink. this does tell me that the issue is not to do with strange duplicates but moodles actually not rendering (beforehand it'd only happened with moodles that aren't very important so i couldn't tell)

**Comment by demiurgeQuantified** [comment]
^ was not meant to close it, fix has not been thoroughly tested

**Comment by demiurgeQuantified** [comment]
fix seems to have worked! some more investigation needs to be done on why this happens in the first place but the patch correctly detects and fixes it when it happens
