### ISSUE TITLE
Reimplement Moodles

### ISSUE THREAD

**Issue by demiurgeQuantified** [demiurgeQuantified/StatsAPI#6]
A reimplementation of moodles that allows the moodles to be customised and allows new moodles to be created would be great. This could also finally make the moodles bigger, which is a highly requested mod. From some basic testing, this seems likely to be possible.

**Comment by Diakon5** [comment]
There is already a MoodlesAPI on the workshop, and it's an estabilished mod

**Comment by demiurgeQuantified** [comment]
moodles framework wouldn't allow the default moodles to be changed whatsoever (so no bigger moodles). also, it doesn't support splitscreen

**Comment by demiurgeQuantified** [comment]
completed in v0.4.0
